name: .ECR
on:
  workflow_call:
    inputs:
      environment:
        description: 'The name of the environment to deploy to'
        required: true
        default: 'prod'
        type: string
      tag:
        description: 'The tag of the containers to push'
        default: 'latest'
        type: string
        required: false
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  packages: read # This is required for pushing to ECR and GHCR
jobs:
  ecr:
    name:  ECR
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        package: [backend]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: gha-ecr-push
          aws-region: ca-central-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull, tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GHCR_IMAGE: ghcr.io/${{ github.repository }}/${{ matrix.package }}:${{ inputs.tag }}
        run: |
          # Pull image from GHCR
          docker pull $GHCR_IMAGE || { echo "Error: Failed to pull image $GHCR_IMAGE"; exit 1; }
          
          # Tag for ECR
          ECR_IMAGE=$ECR_REGISTRY/${{ github.repository }}/${{ matrix.package }}:${{ inputs.tag }}
          docker tag $GHCR_IMAGE $ECR_IMAGE
          
          # Push to ECR
          docker push $ECR_IMAGE