name: .Stack Prefix
on:
  workflow_call:
    outputs:
      STACK_PREFIX: 
        description: 'The Stack Prefix'
        value: ${{ jobs.prefix.outputs.STACK_PREFIX }}
permissions:
  contents: write # This is required for actions/checkout
jobs:
  prefix:
    name: Stack Prefix
    runs-on: ubuntu-24.04
    outputs:
      STACK_PREFIX: ${{ steps.stack-prefix.outputs.STACK_PREFIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Stack Prefix
        id: stack-prefix
        shell: bash
        run: |
          # Get repository name
          STACK_PREFIX=$(echo -n "${{ github.event.repository.name }}" | md5sum | cut -c 1-10) # Default to a hash of the repo name with first 10 characters
          # Set output
          echo "STACK_PREFIX=$STACK_PREFIX" >> $GITHUB_OUTPUT
          echo "Generated prefix: $STACK_PREFIX"