name: .Stack Prefix
on:
  workflow_call:
    outputs:
      STACK_PREFIX: 
        description: 'The Stack Prefix'
        value: ${{ jobs.prefix.outputs.STACK_PREFIX }}
permissions:
  contents: write # This is required for actions/checkout
jobs:
  prefix:
    name: Stack Prefix
    runs-on: ubuntu-24.04
    outputs:
      STACK_PREFIX: ${{ steps.stack-prefix.outputs.STACK_PREFIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Stack Prefix
        id: stack-prefix
        shell: bash
        run: |
          # Get repository name
          # Extract repository name from GITHUB_REPOSITORY (format: owner/repo)
          REPO_NAME=${{ github.event.repository.name }}
          # Check if repository name length is less than 31 characters
          if [ ${#REPO_NAME} -lt 31 ]; then
            STACK_PREFIX="$REPO_NAME"
            echo "Using full repository name as stack prefix"
          else
            STACK_PREFIX="${REPO_NAME:0:30}"
            echo "Repository name too long, truncated to 30 characters"
          fi
          # Remove any invalid characters (only alphanumeric and hyphens allowed for stack names)
          STACK_PREFIX=$(echo "$STACK_PREFIX" | tr -cd 'a-zA-Z0-9-')
          # Set output
          echo "STACK_PREFIX=$STACK_PREFIX" >> $GITHUB_OUTPUT
          echo "Generated prefix: $STACK_PREFIX"